// SPDX-License-Identifier: MPL-2.0
#include "editor/SelectionText.hpp"

#include <algorithm>
#include <utility>

namespace rivet::editor {

std::vector<TextRange> orderedSelectionRanges(
    const TextSelection& selection,
    const std::function<std::size_t(core::PageId)>& indexOf,
    const std::function<core::PageId(std::size_t)>& pageAt,
    std::size_t invalidIndex) {
    std::vector<TextRange> ranges;
    if (selection.empty()) return ranges;
    const std::size_t anchorIndex = indexOf(selection.anchor.page);
    const std::size_t focusIndex = indexOf(selection.focus.page);
    if (anchorIndex == invalidIndex || focusIndex == invalidIndex) return ranges;

    // Order the two ends: by page position, then by character index.
    TextPosition first = selection.anchor;
    TextPosition last = selection.focus;
    std::size_t firstIndex = anchorIndex;
    std::size_t lastIndex = focusIndex;
    if (focusIndex < anchorIndex ||
        (focusIndex == anchorIndex && selection.focus.characterIndex < selection.anchor.characterIndex)) {
        std::swap(first, last);
        std::swap(firstIndex, lastIndex);
    }

    if (firstIndex == lastIndex) {
        ranges.push_back(TextRange{first.page, first.characterIndex, last.characterIndex});
        return ranges;
    }
    ranges.reserve(lastIndex - firstIndex + 1);
    ranges.push_back(TextRange{first.page, first.characterIndex, TextRange::kToPageEnd});
    for (std::size_t index = firstIndex + 1; index < lastIndex; ++index) {
        ranges.push_back(TextRange{pageAt(index), 0, TextRange::kToPageEnd});
    }
    ranges.push_back(TextRange{last.page, 0, last.characterIndex});
    return ranges;
}

void appendCodePointUtf8(std::string& out, char32_t codePoint) {
    if ((codePoint >= 0xD800u && codePoint <= 0xDFFFu) || codePoint > 0x10FFFFu) codePoint = 0xFFFDu;
    if (codePoint <= 0x7Fu) {
        out.push_back(static_cast<char>(codePoint));
    } else if (codePoint <= 0x7FFu) {
        out.push_back(static_cast<char>(0xC0u | (codePoint >> 6)));
        out.push_back(static_cast<char>(0x80u | (codePoint & 0x3Fu)));
    } else if (codePoint <= 0xFFFFu) {
        out.push_back(static_cast<char>(0xE0u | (codePoint >> 12)));
        out.push_back(static_cast<char>(0x80u | ((codePoint >> 6) & 0x3Fu)));
        out.push_back(static_cast<char>(0x80u | (codePoint & 0x3Fu)));
    } else {
        out.push_back(static_cast<char>(0xF0u | (codePoint >> 18)));
        out.push_back(static_cast<char>(0x80u | ((codePoint >> 12) & 0x3Fu)));
        out.push_back(static_cast<char>(0x80u | ((codePoint >> 6) & 0x3Fu)));
        out.push_back(static_cast<char>(0x80u | (codePoint & 0x3Fu)));
    }
}

void appendRangeText(const pdf::PdfTextPage& page, std::uint32_t begin, std::uint32_t end,
                     std::string& out) {
    const std::vector<pdf::TextChar>& chars = page.chars();
    const std::size_t stop = std::min<std::size_t>(end, chars.size());
    for (std::size_t c = begin; c < stop; ++c) {
        const pdf::TextChar& ch = chars[c];
        if (ch.bounds.isEmpty() && (ch.unicode == U'\r' || ch.unicode == U'\n')) {
            // "\r\n" pairs generated by the extractor become one '\n'.
            if (ch.unicode == U'\n' && !out.empty() && c > begin && chars[c - 1].unicode == U'\r' &&
                chars[c - 1].bounds.isEmpty()) {
                continue;
            }
            out.push_back('\n');
            continue;
        }
        if (ch.unicode == 0xFFFDu && ch.bounds.isEmpty()) continue; // no geometry, no text
        appendCodePointUtf8(out, ch.unicode);
    }
}

} // namespace rivet::editor
