// SPDX-License-Identifier: MPL-2.0

#include "pdf/BundledFonts.hpp"

#include "pdf/BundledFontData.hpp"

#include <algorithm>
#include <array>
#include <cstddef>

namespace rivet::pdf {

namespace {

struct CodepointRange {
    char32_t first;
    char32_t last;
};

// Generated by tools/fonts/subset_fonts.py: kCoverage<Face>[] sorted ranges.
#include "pdf/BundledFontCoverage.inc"

struct Coverage {
    const CodepointRange* ranges;
    std::size_t count;
};

template <std::size_t N>
constexpr Coverage coverageOf(const CodepointRange (&ranges)[N]) {
    return Coverage{ranges, N};
}

// Indexed by PdfBundledFont.
constexpr std::array<Coverage, 6> kCoverage = {
    coverageOf(kCoverageSansRegular), coverageOf(kCoverageSansBold),
    coverageOf(kCoverageSerifRegular), coverageOf(kCoverageSerifBold),
    coverageOf(kCoverageMonoRegular), coverageOf(kCoverageMonoBold),
};

constexpr std::array<const char*, 6> kDisplayNames = {
    "Arimo Regular", "Arimo Bold", "Tinos Regular", "Tinos Bold", "Cousine Regular", "Cousine Bold",
};

std::size_t indexOf(PdfBundledFont font) {
    const auto index = static_cast<std::size_t>(font);
    return index < kCoverage.size() ? index : 0;
}

} // namespace

std::span<const std::uint8_t> bundledFontData(PdfBundledFont font) {
    return embeddedFontData(indexOf(font));
}

std::string_view bundledFontDisplayName(PdfBundledFont font) {
    return kDisplayNames[indexOf(font)];
}

bool bundledFontCovers(PdfBundledFont font, char32_t codepoint) {
    // Line breaks and spaces are always accepted: the layout consumes them
    // and never asks the font for a glyph.
    if (codepoint == U'\n' || codepoint == U'\r' || codepoint == U'\t' || codepoint == U' ') return true;
    const Coverage& coverage = kCoverage[indexOf(font)];
    const CodepointRange* end = coverage.ranges + coverage.count;
    // First range whose last >= codepoint.
    const CodepointRange* it = std::lower_bound(
        coverage.ranges, end, codepoint,
        [](const CodepointRange& range, char32_t value) { return range.last < value; });
    return it != end && it->first <= codepoint;
}

PdfBundledFont fallbackFor(const PdfFontInfo& original) {
    if (original.monospace) {
        return original.bold ? PdfBundledFont::MonoBold : PdfBundledFont::MonoRegular;
    }
    if (original.serif) {
        return original.bold ? PdfBundledFont::SerifBold : PdfBundledFont::SerifRegular;
    }
    return original.bold ? PdfBundledFont::SansBold : PdfBundledFont::SansRegular;
}

} // namespace rivet::pdf
