// SPDX-License-Identifier: MPL-2.0

#pragma once

#include "core/geometry/Rect.hpp"

#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

namespace rivet::pdf {

// One extracted character. bounds is the char box in DISPLAYED-PAGE space
// (points, origin at the top-left of the displayed page, y-down, /Rotate
// applied - the same space as PdfDocument::renderPage's pageRectPoints).
// Line-break characters generated by the extractor (e.g. 0x0D) have an empty
// (zero-area) bounds.
struct TextChar {
    char32_t unicode = 0xFFFD; // UCS-4 code point
    std::uint32_t index = 0;   // page-local character index
    core::Rect bounds;         // displayed-page points
    double fontSize = 0.0;     // em size in points
};

// Immutable, Rivet-owned text of one page. Holds no engine handles: safe to
// cache, share across threads as a shared_ptr<const T>, and outlive any
// engine call.
//
// Chars are stored in the extractor's reading order with consecutive page
// indexes 0..n-1. The constructor precomputes the UTF-8 text and a row index
// (rows = chars clustered by y-center of their bounds) used by range
// rectangles and hit testing.
class PdfTextPage {
public:
    PdfTextPage() = default;

    // Chars must have consecutive indexes 0..n-1 (the extractor guarantees
    // this; the constructor does not renumber).
    explicit PdfTextPage(std::vector<TextChar> chars);

    std::size_t charCount() const { return chars_.size(); }
    const std::vector<TextChar>& chars() const { return chars_; }

    // Full text as UTF-8, one code point per TextChar (same order/indexes).
    // Invalid code points (surrogates, above U+10FFFF) are encoded as
    // U+FFFD so the string is always valid UTF-8.
    const std::string& text() const { return text_; }

    // Estimated memory footprint in bytes (chars + text + row index) for the
    // editor-side byte-bounded cache. Good-faith estimate, not exact.
    std::size_t memoryBytes() const;

    // Rectangles covering characters [start, start+count) at line/run
    // granularity (displayed-page points) - for selection and search
    // highlights. Chars on the same text row are merged into one rect per
    // row; zero-area chars (line breaks) contribute nothing. The range is
    // clamped into [0, charCount). Empty when the (clamped) range is empty.
    std::vector<core::Rect> rectsForRange(std::uint32_t start, std::uint32_t count) const;

    // Page-local hit test: the character index nearest a displayed-page
    // point, using the row index built at construction. Rules:
    //   - pick the row whose y-center is nearest the point (ties -> the
    //     earlier row);
    //   - within the row, the char whose x-center is nearest the point
    //     (ties -> the earlier char);
    //   - nullopt when the page has no selectable chars (empty page or only
    //     zero-area chars).
    std::optional<std::uint32_t> charIndexAtPoint(const core::Point& point) const;

private:
    // Row index: one entry per cluster of selectable chars, with the char
    // index range [first, last] in ORIGINAL index order (chars are already
    // in reading order per the extractor). Zero-area chars are not rows of
    // their own but may fall inside a row's index range (e.g. generated
    // spaces); a generated line break between rows falls outside every row.
    struct Row {
        double yCenter = 0.0;        // mean y-center of the row's char boxes
        std::uint32_t first = 0;     // first char index (inclusive)
        std::uint32_t last = 0;      // last char index (inclusive)
    };

    void buildRowIndex();

    // The row whose index range contains `index`, or nullptr. Rows have
    // disjoint, ascending ranges.
    const Row* rowContainingIndex(std::uint32_t index) const;

    std::vector<TextChar> chars_;
    std::string text_;
    std::vector<Row> rows_;
};

// One search match: page-local character range [startIndex, startIndex+count).
struct TextSearchResult {
    std::uint32_t startIndex = 0;
    std::uint32_t count = 0;
    bool operator==(const TextSearchResult&) const = default;
};

// Options for searchTextPage.
struct TextSearchOptions {
    bool caseSensitive = false;
    bool wholeWord = false;
};

// Searches the page text for `needle` (UTF-8) and returns every match in
// page order. Matching runs on the UTF-32 view of the page text (one unit
// per TextChar, so match indexes are page-local char indexes). Case
//-insensitive matching is Unicode-aware via foldCodePoint (NOT ASCII-only).
// Overlapping matches are not produced: the scan resumes after each match.
// Empty needle -> no results.
std::vector<TextSearchResult> searchTextPage(const PdfTextPage& page,
                                             std::string_view needle,
                                             const TextSearchOptions& options = {});

// Simple Unicode default case folding for the ranges Rivet supports without
// ICU: ASCII, Latin-1 Supplement, Greek, Cyrillic (U+0400..U+040F fold onto
// +0x50, U+0410..U+042F onto +0x20, and the paired uppercase/lowercase
// runs from U+0460 on fold even/odd onto +1), plus the obvious U+0178 ->
// U+00FF and the U+1E00.. paired runs. Unknown code points fold to
// themselves.
//
// LIMITATION: this is a hand-written subset, not full Unicode case folding
// (no special cases like final sigma, no Turkish/Azeri dotless rules, no
// astral-plane pairs). Full folding needs ICU and is out of scope here.
char32_t foldCodePoint(char32_t codePoint);

// Word-character test for wholeWord matching: ASCII letters/digits,
// underscore, and the Latin-1/Greek/Cyrillic letter ranges covered by
// foldCodePoint.
bool isWordChar(char32_t codePoint);

} // namespace rivet::pdf
