# SPDX-License-Identifier: MPL-2.0
#
# Build-time font embedding, run as a script by add_custom_command:
#
#   cmake -DFONT_DIR=<dir> -DOUTPUT=<file.cpp> -DFONTS=<a.ttf;b.ttf;...> -P EmbedFonts.cmake
#
# Writes a C++ file defining rivet::pdf::embeddedFontData(index) (declared in
# src/pdf/BundledFontData.hpp) that returns the bytes of the index-th font of
# FONTS. Only CMake is needed; no external tool, no network.

if(NOT DEFINED FONT_DIR OR NOT DEFINED OUTPUT OR NOT DEFINED FONTS)
    message(FATAL_ERROR "EmbedFonts.cmake: FONT_DIR, OUTPUT and FONTS are required")
endif()

set(_text "// SPDX-License-Identifier: MPL-2.0\n// GENERATED by cmake/EmbedFonts.cmake - do not edit.\n\n")
string(APPEND _text "#include \"pdf/BundledFontData.hpp\"\n\n#include <cstddef>\n#include <cstdint>\n\nnamespace rivet::pdf {\n\nnamespace {\n\n")

set(_index 0)
foreach(_font IN LISTS FONTS)
    file(READ "${FONT_DIR}/${_font}" _hex HEX)
    string(LENGTH "${_hex}" _hexLength)
    math(EXPR _size "${_hexLength} / 2")
    # Two hex digits per byte -> "0xNN,"; a newline every 16 bytes.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" _bytes "${_bytes}")
    string(APPEND _text "constexpr std::uint8_t kFont${_index}[] = {\n${_bytes}\n};\n\n")
    list(APPEND _sizes "${_size}")
    math(EXPR _index "${_index} + 1")
endforeach()

string(APPEND _text "} // namespace\n\nstd::span<const std::uint8_t> embeddedFontData(std::size_t index) {\n    switch (index) {\n")
set(_index 0)
foreach(_font IN LISTS FONTS)
    string(APPEND _text "    case ${_index}:\n        return std::span<const std::uint8_t>(kFont${_index}, sizeof(kFont${_index}));\n")
    math(EXPR _index "${_index} + 1")
endforeach()
string(APPEND _text "    default:\n        return {};\n    }\n}\n\n} // namespace rivet::pdf\n")

# Rewrite only on change so an unchanged font set does not retrigger the compile.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _existing)
else()
    set(_existing "")
endif()
if(NOT "${_existing}" STREQUAL "${_text}")
    file(WRITE "${OUTPUT}" "${_text}")
endif()
